# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: my_service.proto

require "google/protobuf"


descriptor_data = "\n\x10my_service.proto\x12\nmy_service\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t2G\n\x07Greeter\x12<\n\x08SayHello\x12\x18.my_service.HelloRequest\x1a\x16.my_service.HelloReplyb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module MyService
	HelloRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("my_service.HelloRequest").msgclass
	HelloReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("my_service.HelloReply").msgclass
end
