# frozen_string_literal: true

# A sample Gemfile
source "https://rubygems.org"

gem "sinatra"
gem "falcon", path: "../.."

# Rack dependency:

gem "rack", "~> 2.0"
# or:
# gem "rack", "~> 3.0"
# gem "rackup"
