name: Rack Head

on: [push, pull_request]

permissions:
  contents: read

env:
  CONSOLE_OUTPUT: XTerm

jobs:
  test:
    runs-on: ${{matrix.os}}-latest
    
    strategy:
      matrix:
        os:
          - ubuntu
        
        ruby:
          - "2.7"
          - "3.0"
          - "3.1"
    
    env:
      BUNDLE_GEMFILE: gems/rack-head.rb
    
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby}}
        bundler-cache: true
    
    - name: Installing packages (ubuntu)
      if: matrix.os == 'ubuntu'
      run: sudo apt-get install apache2-utils
    
    - name: Run tests
      timeout-minutes: 5
      run: bundle exec rspec
